create table if not exists public.site_settings (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id, data)
values (
  'main',
  '{
    "contact": {
      "phoneDisplay": "+225 07 77 73 47 76",
      "email": "otakkos007@gmail.com",
      "whatsappNumber": "2250777734776"
    },
    "jobs": [],
    "restaurants": [],
    "menu": null
  }'::jsonb
)
on conflict (id) do nothing;

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('visit', 'interaction')),
  page text,
  label text,
  created_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;
alter table public.site_events enable row level security;

drop policy if exists "Public can read site settings" on public.site_settings;
drop policy if exists "Admins can insert site settings" on public.site_settings;
drop policy if exists "Admins can update site settings" on public.site_settings;
drop policy if exists "Admins can delete site settings" on public.site_settings;
drop policy if exists "Public can insert site events" on public.site_events;
drop policy if exists "Admins can read site events" on public.site_events;

create policy "Public can read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

create policy "Admins can insert site settings"
on public.site_settings
for insert
to authenticated
with check (true);

create policy "Admins can update site settings"
on public.site_settings
for update
to authenticated
using (true)
with check (true);

create policy "Admins can delete site settings"
on public.site_settings
for delete
to authenticated
using (true);

create policy "Public can insert site events"
on public.site_events
for insert
to anon, authenticated
with check (true);

create policy "Admins can read site events"
on public.site_events
for select
to authenticated
using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-uploads',
  'site-uploads',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read uploaded site files" on storage.objects;
drop policy if exists "Admins can upload site files" on storage.objects;
drop policy if exists "Admins can update site files" on storage.objects;
drop policy if exists "Admins can delete site files" on storage.objects;

create policy "Public can read uploaded site files"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'site-uploads');

create policy "Admins can upload site files"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'site-uploads');

create policy "Admins can update site files"
on storage.objects
for update
to authenticated
using (bucket_id = 'site-uploads')
with check (bucket_id = 'site-uploads');

create policy "Admins can delete site files"
on storage.objects
for delete
to authenticated
using (bucket_id = 'site-uploads');
